### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by ShayanTheNerd** [LieutenantPeacock/SmoothScroll#1]
Hi, thanks for creating and maintaining this project. I'd really appreciate it if you publish the package on NPM to allow for modular usage.

Also, as a side note, I believe there are parts of the source code that you can update and refactor to privilege newer, well-supported JS syntax and features.

**Comment by artursharipov** [comment]
How can I embed Vue 2 into a component as a module?

**Comment by LieutenantPeacock** [comment]
Thanks for opening this issue! I've now renamed the library and published it to NPM. 

You can install it by running `npm i fluidscroll` and then use it like this:

```js
import { fluidScroll } from 'fluidscroll';
```

I was not using newer JavaScript features as one of the main features of this library is the high level of support for older browsers. However, I may rewrite the code at some point and add TypeScript as well.
